# functions:
esperanto_builtins = {
"AritmetikoEraro" :'ArithmeticError',
"" : 'AssertionError',
"" : 'AttributeError',
"" : 'BaseException',
"" : 'BlockingIOError',
"" : 'BrokenPipeError',
"" : 'BufferError',
"BitokojAverto" : 'BytesWarning',
"" : 'ChildProcessError',
"" : 'ConnectionAbortedError',
"" : 'ConnectionError',
"" : 'ConnectionRefusedError',
"" : 'ConnectionResetError',
"" : 'DeprecationWarning',
"FDDEraro" : 'EOFError',
"" : 'Ellipsis',
"" : 'EnvironmentError',
"Escepto" : 'Exception',
"" : 'FileExistsError',
"DosieroNeTrovitaEraro" : 'FileNotFoundError',
"" : 'FloatingPointError',
"" : 'FutureWarning',
"" : 'GeneratorExit',
"EneligoEraro" : 'IOError',
"ImportadoEraro" : 'ImportError',
"ImportadoAverto" : 'ImportWarning',
"" : 'IndentationError',
"" : 'IndexError',
"" : 'InterruptedError',
"" : 'IsADirectoryError',
"" : 'KeyError',
"" : 'KeyboardInterrupt',
"" : 'LookupError',
"" : 'MemoryError',
"" : 'ModuleNotFoundError',
"NomoEraro" : 'NameError',
"" : 'NotADirectoryError',
"" : 'NotImplemented',
"" : 'NotImplementedError',
"MastrumiloEraro" : 'OSError',
"SuperfluoEraro" : 'OverflowError',
"" : 'PendingDeprecationWarning',
"PermesoEraro" : 'PermissionError',
"" : 'ProcessLookupError',
"" : 'RecursionError',
"" : 'ReferenceError',
"" : 'ResourceWarning',
"RultempoEraro" : 'RuntimeError',
"RultempoAverto" : 'RuntimeWarning',
"" : 'StopAsyncIteration',
"" : 'StopIteration',
"SintaksoEraro" : 'SyntaxError',
"SintaksoAverto" : 'SyntaxWarning',
"SistemoEraro" : 'SystemError',
"SistemoEksiĝi" : 'SystemExit',  # TODO renomi
"" : 'TabError',
"" : 'TimeoutError',
"TipoEraro" : 'TypeError',
"" : 'UnboundLocalError',
"UnikodoMalkodiEraro" : 'UnicodeDecodeError',
"UnikodoKodiEraro" : 'UnicodeEncodeError',
"UnikodoEraro" : 'UnicodeError',
"UnikodoTradukiEraro" : 'UnicodeTranslateError',
"UnikodoAverto" : 'UnicodeWarning',
"UzantoAverto" : 'UserWarning',
"ValoroEraro" : 'ValueError',
"Averto" : 'Warning',
"NulDivizioEraro" : 'ZeroDivisionError',
# "" : '_',
"" : '__build_class__',
"__necimo__" : '__debug__',  # maybe something else?
"__dok__" : '__doc__',
"__importi__" : '__import__',
"" : '__loader__',
"__nomo__" : '__name__',
"" : '__package__',
"__plano__" : '__spec__',
"abs" : 'abs',
"" : 'aiter',
"ĉio" : 'all',
"" : 'anext',
"io" : 'any',
"askio" : 'ascii',
"bin" : 'bin',  # aŭ binara/duuma?
"bulea" : 'bool',
"" : 'breakpoint',
"" : 'bytearray',
"bitokoj" : 'bytes',
"" : 'callable',
"" : 'chr',
"" : 'classmethod',
"" : 'compile',
"kompleksa" : 'complex',
"kopirajto" : 'copyright',
"" : 'credits',
"" : 'delattr',
"vortaro" : 'dict',  # aŭ vort?
"" : 'dir',
"" : 'divmod',
"nombri" : 'enumerate',
"" : 'eval',
"ekzek" : 'exec',
"eksiĝi" : 'exit',  # TODO renomi
"" : 'filter',
"glitkomo" : 'float',  # nur "glit"
"" : 'format',
"frostaro" : 'frozenset',
"" : 'getattr',
"mallokaj" : 'globals',
"" : 'hasattr',
"" : 'hash',
"helpi" : 'help',
"dekses" : 'hex',  # aŭ deksesuma
"legitimilo" : 'id',  # eble malpli granda?
"enigo" : 'input',
"entjero" : 'int',  # nur "ent"?
"estasklaso" : 'isinstance',
"" : 'issubclass',
"" : 'iter',
"longo" : 'len',
"" : 'license',
"listo" : 'list',
"lokaj" : 'locals',
"mapi" : 'map',
"maks" : 'max',
"" : 'memoryview',
"min" : 'min',
"sekva" : 'next',
"objekto" : 'object',
"okuma" : 'oct',
"malfermi" : 'open',
"" : 'ord',
"potenco" : 'pow',
"presi" : 'print',
"" : 'property',
"eksiĝi" : 'quit',
"intervalo" : 'range',
"repr" : 'repr',
"inversa" : 'reversed',
"rondigi" : 'round',
"aro" : 'set',
"" : 'setattr',
"tranĉaĵo" : 'slice',
"ordigita" : 'sorted',
"" : 'staticmethod',
"teksto" : 'str',
"sumo" : 'sum',
"" : 'super',
"" : 'tuple',
"tipo" : 'type',
"" : 'vars',
"" : 'zip'}

# keywords:
esperanto_keywords = {
    # "pitono": "esperanto_python",
    # if and booleans:
    "Malvera": "False",
    "Nul": "None",
    "Vera": "True",
    "kaj": "and",
    "kiel": "as",
    "aserti": "assert",
    "nesink": "async",
    "atendi": "await",
    "interrompi": "break",
    "klaso": "class",
    "daŭrigi": "continue",
    "dif": "def",
    "forigi": "del",
    "alse": "elif",
    "alie": "else",
    "trakti": "except",  # aŭ krom?
    "fine": "finally",
    "por": "for",
    "el": "from",
    "malloka": "global",
    "se": "if",
    "importi": "import",
    "en": "in",
    "estas": "is",
    "lambda": "lambda",
    "neloka": "nonlocal",
    "ne": "not",
    "aŭ": "or",
    "pasi": "pass",
    "altigi": "raise",  # aŭ levi?
    "redoni": "return",
    "provi": "try",
    "dum": "while",
    "kun": "with",
    "doni": "yield",
}
