# functions:
esperanto_builtins = {
"AritmetikoEraro" :'ArithmeticError',
"AsertoEraro" : 'AssertionError',
"AtributoEraro" : 'AttributeError',
"" : 'BaseException',
"" : 'BlockingIOError',
"" : 'BrokenPipeError',
"BufroEraro" : 'BufferError',
"BajtojAverto" : 'BytesWarning',
"" : 'ChildProcessError',
"" : 'ConnectionAbortedError',
"" : 'ConnectionError',
"" : 'ConnectionRefusedError',
"" : 'ConnectionResetError',
"" : 'DeprecationWarning',
"FDDEraro" : 'EOFError',
"Tripunkto" : 'Ellipsis',
"ĈirkaŭaĵoEraro" : 'EnvironmentError',
"Escepto" : 'Exception',
"DosieroEkzistasEraro" : 'FileExistsError',
"DosieroNeTrovitaEraro" : 'FileNotFoundError',
"GlitkomoEraro" : 'FloatingPointError',
"EstontecoAverto" : 'FutureWarning',
"" : 'GeneratorExit',
"EneligoEraro" : 'IOError',
"ImportadoEraro" : 'ImportError',
"ImportadoAverto" : 'ImportWarning',
"KrommarĝenoEraro" : 'IndentationError',
"IndeksoEraro" : 'IndexError',
"InterrompitaEraro" : 'InterruptedError',
"EstasDosierujoEraro" : 'IsADirectoryError',
"ŜlosiloEraro" : 'KeyError',
"KlavaroInterrompo" : 'KeyboardInterrupt',
"ElserĉoEraro" : 'LookupError',
"MemoroEraro" : 'MemoryError',
"" : 'ModuleNotFoundError',
"NomoEraro" : 'NameError',
"NeEstasDosierujoEraro" : 'NotADirectoryError',
"SenEfektivigo" : 'NotImplemented',
"SenEfektivigoEraro" : 'NotImplementedError',
"MastrumiloEraro" : 'OSError',
"SuperfluoEraro" : 'OverflowError',
"" : 'PendingDeprecationWarning',
"PermesoEraro" : 'PermissionError',
"" : 'ProcessLookupError',
"RikuroEraro" : 'RecursionError',
"ReferencoEraro" : 'ReferenceError',
"RisurcoAverto" : 'ResourceWarning',
"RultempoEraro" : 'RuntimeError',
"RultempoAverto" : 'RuntimeWarning',
"" : 'StopAsyncIteration',
"ĈesigiIteracion" : 'StopIteration',
"SintaksoEraro" : 'SyntaxError',
"SintaksoAverto" : 'SyntaxWarning',
"SistemoEraro" : 'SystemError',
"SistemoElirado" : 'SystemExit',  # TODO renomi
"" : 'TabError',
"TempolimoEraro" : 'TimeoutError',
"TipoEraro" : 'TypeError',
"" : 'UnboundLocalError',
"UnikodoMalkodiEraro" : 'UnicodeDecodeError',
"UnikodoKodiEraro" : 'UnicodeEncodeError',
"UnikodoEraro" : 'UnicodeError',
"UnikodoTradukiEraro" : 'UnicodeTranslateError',
"UnikodoAverto" : 'UnicodeWarning',
"UzantoAverto" : 'UserWarning',
"ValoroEraro" : 'ValueError',
"Averto" : 'Warning',
"NulDivizioEraro" : 'ZeroDivisionError',
# "" : '_',
"__fari_klason__" : '__build_class__',
"__necimo__" : '__debug__',  # maybe something else?
"__dok__" : '__doc__',
"__importi__" : '__import__',
"__ŝargilo__" : '__loader__',
"__nomo__" : '__name__',
"__pako__" : '__package__',
"__plano__" : '__spec__',
"abs" : 'abs',
"nesinkiter" : 'aiter',
"ĉio" : 'all',
"nesinksekva" : 'anext',
"io" : 'any',
"askio" : 'ascii',
"bin" : 'bin',  # aŭ binara/duuma?
"bulea" : 'bool',
"paŭzpunkto" : 'breakpoint',
"bajtatabelo" : 'bytearray',
"bajtoj" : 'bytes',
"alvokebla" : 'callable',
"signo" : 'chr',
"klasmetodo" : 'classmethod',
"kompili" : 'compile',
"kompleksa" : 'complex',
"kopirajto" : 'copyright',
"agnoskoj" : 'credits',
"forigiatr" : 'delattr',
"vortaro" : 'dict',  # aŭ vort?
"dosierujo" : 'dir',  # aŭ dos?
"divrest" : 'divmod',
"nombri" : 'enumerate',
"kalkuli" : 'eval',
"ruli" : 'exec',  # aŭ plenumi
"eliri" : 'exit',  # TODO renomi
"filtri" : 'filter',
"glitkomo" : 'float',  # nur "glit"
"formi" : 'format',  # aŭ formati?
"frostaro" : 'frozenset',
"akiriatr" : 'getattr',
"mallokaj" : 'globals',
"havasatr" : 'hasattr',
"haketo" : 'hash',
"helpi" : 'help',
"dekses" : 'hex',  # aŭ deksesuma
"legitimilo" : 'id',  # eble malpli granda?
"enigo" : 'input',
"entjero" : 'int',  # nur "ent"?
"estasklaso" : 'isinstance',
"estassubklaso" : 'issubclass',
"iter" : 'iter',  # iteracii
"longo" : 'len',
"permesilo" : 'license',
"listo" : 'list',
"lokaj" : 'locals',
"mapi" : 'map',
"maks" : 'max',
"memoravido" : 'memoryview',
"min" : 'min',
"sekva" : 'next',
"objekto" : 'object',
"okuma" : 'oct',
"malfermi" : 'open',
"numero" : 'ord',
"potenco" : 'pow',
"presi" : 'print',
"eco" : 'property',
"eksiĝi" : 'quit',
"intervalo" : 'range',
"repr" : 'repr',
"inversa" : 'reversed',
"rondigi" : 'round',
"aro" : 'set',
"difiniatr" : 'setattr',
"tranĉaĵo" : 'slice',
"ordigita" : 'sorted',
"statikametodo" : 'staticmethod',
"teksto" : 'str',
"sumo" : 'sum',
"super" : 'super',
"opo" : 'tuple',
"tipo" : 'type',
"variabloj" : 'vars',
"densigi" : 'zip'}

# keywords:
esperanto_keywords = {
    "Malvera": "False",
    "Nul": "None",
    "Vera": "True",
    "kaj": "and",
    "kiel": "as",
    "aserti": "assert",
    "nesink": "async",
    "atendi": "await",
    "interrompi": "break",
    "klaso": "class",
    "daŭrigi": "continue",
    "dif": "def",
    "forigi": "del",
    "alse": "elif",
    "alie": "else",
    "trakti": "except",  # aŭ krom?
    "fine": "finally",
    "por": "for",
    "el": "from",
    "malloka": "global",
    "se": "if",
    "importi": "import",
    "en": "in",
    "estas": "is",
    "lambda": "lambda",
    "neloka": "nonlocal",
    "ne": "not",
    "aŭ": "or",
    "pasi": "pass",
    "altigi": "raise",  # aŭ levi?
    "redoni": "return",
    "provi": "try",
    "dum": "while",
    "kun": "with",
    "doni": "yield",
}
